### PR TITLE
Add Blockchain Commons

### PR DESCRIPTION
**Pull request by ChristopherA**

### CODE REVIEW

**Comment by ChristopherA** [comment]
Tried twice, 2nd time changing # to &#35; — not sure what is causing lint error.

**Comment by modl21** [comment]
fixed the error but not sure if we should add projects to the list, so far list is individuals only? anyone else have thoughts here?

**Comment by Zaxounette** [comment]
The subtitle on the website states the following:
`Support bitcoin developers so they can focus on building our future`

And the introductory § states the following:
`This website lists people working on Bitcoin and related projects. The goal is to increase the visibility of contributors to the space that are accepting donations.`

Given these, i'd advocate to keeping the list specific to individuals.

**Comment by modl21** [comment]
That's my feeling as well but we could either add a separate page for organizations or put it as a tag that can be sorted by the user (along with other tags such as lightning, privacy, ux, etc.).

**Comment by ChristopherA** [comment]
I know for orgs it is more complicated. They often have more options than one for donations (fiat & btc), and some are non-profits in their nation and are considered charitable contributions in that nation. For instance Blockchain Commons is not a US charitable non-profit and if a US citizen someone needs that for a larger donation we send elsewhere first. 

Related, though I work for Blockchain Commons, I have my own independent sponsor link for my personal work, as do others that are at Blockchain Commons. I suspect there may other orgs with individuals the same.

**Comment by Coinward** [comment]
I think it makes sense to add ChristopherA, and less sense to add Blockchain Commons

**Comment by modl21** [comment]
Christopher has already been added individually and so has Fontaine who also works with him at blockchain commons. I am going to close this PR for now and we can revisit it if we decide to add organizations. Either through a tag + sorting or as a separate page  - which I think we probably should do at some point.

**Comment by ChristopherA** [comment]
I’m +1 for not including @BlockchainCommons is this list of individuals.

But for the record, both @Fonta1ne & I have personal bitcoin related projects outside of the scope of @BlockchainCommons, as do other contributors. Figuring out how to provide clarity here for future Patrons would be useful toward creating a sustainable ecosystem in the future.

**Comment by modl21** [comment]
Understood and agree. Let’s continue this discussion here: https://github.com/dennisreimann/bitcoin-donations/issues/12#issue-669101903

**Pull request closed without merging**
