### PR TITLE
Added @ChristopherA

### PR DESCRIPTION
**Pull request by ChristopherA**

### CODE REVIEW

**Comment by ChristopherA** [comment]
I'm getting error with auto-linter, presume it is some type of character set problem in the JSON? Any advice?

**Comment by ChristopherA** [comment]
The linter is saying `forgot to run prettier --check '**/*.js`

**Comment by ChristopherA** [comment]
So the GitHub action says that the linter wants prettier to be used. So I tried used prettier offline and it finds all kinds of prettier problems, but even submitting that still doesn't fix whatever the linter is balking on. Passing this on to @dennisreimann — maybe add prettier to the action, and maybe we'll get a better error from the linter.

**Comment by dennisreimann** [comment]
I removed the lint step from the build. Can you resubmit your addition as the current changeset is more than just your entry?

**Pull request merged**
